# Generated by Django 5.2.6 on 2025-10-11 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_core', '0004_conversation_conversation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=50)),
                ('code_length', models.PositiveIntegerField(help_text='Number of characters in the code')),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, help_text='Execution time in milliseconds', null=True)),
                ('success', models.BooleanField(help_text='Whether the execution was successful')),
                ('error_type', models.CharField(blank=True, max_length=100, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_core.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['user', '-executed_at'], name='execution_c_user_id_4a91b4_idx'), models.Index(fields=['user', 'success'], name='execution_c_user_id_01f3f9_idx')],
            },
        ),
    ]
