# Generated by Django 5.2.17 on 2026-09-02 04:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short label shown in the review queue', max_length=255)),
                ('difficulty', models.CharField(default='easy', max_length=10)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('repetitions', models.IntegerField(default=0)),
                ('ease', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=1)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(blank=True, help_text='The coding problem this item reviews (if problem-based)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_items', to='challenges.codingproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('problem__isnull', False)), fields=('user', 'problem'), name='unique_revision_problem_per_user')],
            },
        ),
    ]
