# Generated by Django 5.2.17 on 2026-09-01 08:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_core', '0006_alter_conversation_conversation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Sequence in the overall curriculum')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SDLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='What this lesson covers')),
                ('order', models.PositiveIntegerField(help_text='Sequence within the course')),
                ('learning_objectives', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='List of concepts the learner should master in this lesson', size=None)),
                ('estimated_duration', models.DurationField(blank=True, help_text='Expected time to complete', null=True)),
                ('reference_diagram', models.JSONField(blank=True, help_text='Optional {nodes, edges} reference architecture to load into the whiteboard', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='system_design.sdcourse')),
            ],
            options={
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserSDCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation', models.OneToOneField(blank=True, help_text='Optional course-level conversation', null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_core.conversation')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='system_design.sdcourse')),
                ('current_lesson', models.ForeignKey(blank=True, help_text='The lesson the user is currently working on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_design.sdlesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course__order'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='SDLessonProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI confidence the user has mastered this lesson (0-1)')),
                ('covered_points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('remaining_points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(blank=True, help_text='Conversation for this lesson', null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_core.conversation')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_design.sdlesson')),
                ('user_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='system_design.usersdcourse')),
            ],
            options={
                'ordering': ['lesson__order'],
                'unique_together': {('user_course', 'lesson')},
            },
        ),
    ]
