# Generated by Django 5.2.17 on 2026-09-02 04:12

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDCaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('overview', models.TextField(help_text='Markdown description of the problem')),
                ('functional_requirements', models.JSONField(default=list, help_text='List of functional requirements')),
                ('non_functional_requirements', models.JSONField(default=list, help_text='List of NFRs')),
                ('capacity', models.JSONField(blank=True, default=dict, help_text='Key-value estimates, e.g. {"DAU": "100M", ...}')),
                ('key_components', models.JSONField(default=list, help_text='List of {name, responsibility}')),
                ('tradeoffs', models.JSONField(default=list, help_text='List of key design tradeoffs')),
                ('reference_diagram', models.JSONField(blank=True, help_text='Canonical {nodes, edges} architecture in React Flow format', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
    ]
