# Generated by Django 5.2.17 on 2026-09-02 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0007_alter_conversation_conversation_type'),
        ('system_design', '0002_sdcasestudy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDPracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_phase', models.PositiveSmallIntegerField(default=1, help_text='Active phase 1..5 of the thinking protocol')),
                ('phase_states', models.JSONField(blank=True, default=dict, help_text='Per-phase state: {phase: {completed, score, notes}}')),
                ('weak_areas', models.JSONField(blank=True, default=list, help_text='Diagnosed weak areas from the drill')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case_study', models.ForeignKey(help_text='The design prompt being practiced against', on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='system_design.sdcasestudy')),
                ('conversation', models.OneToOneField(help_text='The chat room for this practice run', on_delete=django.db.models.deletion.CASCADE, related_name='sd_practice_session', to='ai_core.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd_practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
