# Generated by Django 5.2.6 on 2025-09-21 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('idle', 'Idle - Normal conversation'), ('challenge_active', 'Challenge Active - Waiting for code submission'), ('hint_active', 'Hint Active - Providing hints'), ('feedback_active', 'Feedback Active - Providing feedback'), ('conversation', 'General Conversation')], default='idle', max_length=20)),
                ('last_message_type', models.CharField(blank=True, choices=[('hint', 'Hint'), ('challenge', 'Challenge'), ('feedback', 'Feedback'), ('conversation', 'Conversation')], help_text='Type of the last AI message', max_length=20, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of attempts made for the current challenge')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'Ai')])),
                ('content', models.TextField()),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(blank=True, choices=[('hint', 'Hint'), ('challenge', 'Challenge'), ('feedback', 'Feedback'), ('conversation', 'Conversation')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
