# Generated by Django 5.2.6 on 2025-09-20 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
