# Generated by Django 5.2.6 on 2025-09-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'Javascript'), ('typescript', 'Typescript')], null=True),
        ),
    ]
