# Generated by Django 5.2.6 on 2025-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0003_message_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('general', 'General Chat'), ('learning_path', 'Structured Learning Path')], default='general', help_text='Type of conversation - general chat or structured learning', max_length=20),
        ),
    ]
