# Generated by Django 5.2.17 on 2026-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0004_conversation_conversation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='diagram',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('general', 'General Chat'), ('learning_path', 'Structured Learning Path'), ('system_design', 'System Design')], default='general', help_text='Type of conversation - general chat or structured learning', max_length=20),
        ),
    ]
