# Generated by Django 5.2.17 on 2026-09-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0008_alter_conversation_conversation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('general', 'General Chat'), ('learning_path', 'Structured Learning Path'), ('system_design', 'System Design'), ('system_design_learning', 'System Design Learning'), ('system_design_practice', 'System Design Practice'), ('component_tutor', 'Component Tutor'), ('mock_interview', 'Mock Interview')], default='general', help_text='Type of conversation - general chat or structured learning', max_length=32),
        ),
    ]
