# Generated by Django 5.2.17 on 2026-09-02 04:06

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('description', models.TextField(help_text='Markdown problem statement')),
                ('examples', models.JSONField(blank=True, default=list, help_text='List of {input, output, explanation}')),
                ('constraints', models.JSONField(blank=True, default=list, help_text='List of constraint strings')),
                ('starter_code', models.TextField(blank=True, help_text='Python scaffold for the user')),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='List of {name, stdin, expected_output}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProblemAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=50)),
                ('verdict', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('passed_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='challenges.codingproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'problem'], name='challenges__user_id_bfacdb_idx'), models.Index(fields=['problem', 'verdict'], name='challenges__problem_4f13ca_idx')],
            },
        ),
    ]
