# Generated by Django 5.2.17 on 2026-09-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_problemtutorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='compare_mode',
            field=models.CharField(blank=True, default='exact', help_text="'exact' | 'unordered' | 'unordered_nested' — how the return is compared to expected.", max_length=20),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='entry_point',
            field=models.CharField(blank=True, default='', help_text="Function mode: the method name on Solution to call (e.g. 'twoSum').", max_length=80),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='judge_mode',
            field=models.CharField(choices=[('stdio', 'Stdin/Stdout'), ('function', 'Function (LeetCode-style)')], default='function', help_text='stdio: whole-program stdin/stdout. function: call a method on Solution.', max_length=12),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='param_types',
            field=models.JSONField(blank=True, default=list, help_text="Function mode: per-arg type tags ('json'|'listnode'|'tree'); 'json' passes through."),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='return_type',
            field=models.CharField(blank=True, default='json', help_text="Function mode: 'json'|'listnode'|'tree' — how to serialize the return value.", max_length=20),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='stdio: {name, stdin, expected_output}. function: {name, args, expected}.'),
        ),
    ]
