# Generated by Django 5.2.17 on 2026-09-04 08:24

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_codingproblem_compare_mode_codingproblem_entry_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('problem_slugs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=220), blank=True, default=list, help_text='Ordered problem slugs in this list', size=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
