# Generated by Django 5.2.17 on 2026-09-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_problemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='solution_code',
            field=models.TextField(blank=True, default='', help_text='Reference/optimal solution shown as the editorial'),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='solution_complexity',
            field=models.CharField(blank=True, default='', help_text="e.g. 'O(n) time, O(1) space'", max_length=120),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='solution_explanation',
            field=models.TextField(blank=True, default='', help_text='Short explanation of the approach'),
        ),
    ]
