# Generated by Django 5.2.6 on 2025-09-30 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtopic',
            name='created_by',
            field=models.ForeignKey(default='8e53a016-8907-4946-90bf-2e9508d99f74', help_text='User who created this topic', on_delete=django.db.models.deletion.CASCADE, related_name='created_learning_topics', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
