# Generated by Django 5.2.6 on 2025-10-09 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0002_learningtopic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopicprogress',
            name='ai_confidence',
            field=models.FloatField(default=0.0, help_text="AI's confidence that the user has mastered the subtopic (0-1)"),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='covered_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='List of concepts already covered in this subtopic', size=None),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='remaining_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='List of concepts not yet covered', size=None),
        ),
        migrations.AlterField(
            model_name='subtopicprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20),
        ),
    ]
