# Generated by Django 5.2.6 on 2025-10-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0004_conversation_conversation_type'),
        ('learning_paths', '0003_subtopicprogress_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopicprogress',
            name='conversation',
            field=models.OneToOneField(blank=True, help_text='The conversation associated with this subtopic', null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_core.conversation'),
        ),
    ]
